source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

target 'RecapASRBench' do
  pod 'SocketRocket', '0.6.1'
  pod 'SpeechEngineToB', '0.0.15.0'
end
