
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '12.0'

inhibit_all_warnings!

target 'SpeechDemo' do
    # Add cocoapods dependencyies
    pod 'SPEECH_MODULE_NAME', 'SPEECH_MODULE_VERSION'
end
